FROM  moveit/moveit2:galactic-release

# nvidia-container-runtime
# cf https://stackoverflow.com/a/62354513/11579406 
ENV NVIDIA_VISIBLE_DEVICES ${NVIDIA_VISIBLE_DEVICES:-all}
ENV NVIDIA_DRIVER_CAPABILITIES ${NVIDIA_DRIVER_CAPABILITIES:+$NVIDIA_DRIVER_CAPABILITIES,}graphics