name: CI build

on:
  pull_request:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    container: moveit/moveit2:galactic-release
    steps:
      - uses: actions/checkout@v2
      - run: |
        export COLCON_WS=${GITHUB_WORKSPACE}/ROS
        bash build.sh
        shell: bash
        name: prepare and build
