name: CI build

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container: moveit/moveit2:galactic-release
    steps:
      - uses: actions/checkout@v2
      - run: |
          export COLCON_WS=${GITHUB_WORKPACE}/ROS
      - run: |
          cd ${COLCON_WS}
          ls src/robots/UR/
      - run:
          bash prepare_build.sh
          shell: bash

      - run:
          bash build.sh
          shell: bash
