
name: CI build

on:
  pull_request:
  push:
    branches:
      - main
      - ci

jobs:
  build:
    runs-on: ubuntu-latest
    container: moveit/moveit2:galactic-source
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Setup clang-10
        uses: egor-tensin/setup-clang@v1
        with:
          version: latest
          platform: x64
      - name: actions/precommits
        run: |
          pip3 install pre-commit
          pre-commit run --all-files
      - name: prepare and build
        run: |
          export COLCON_WS=${GITHUB_WORKSPACE}/ROS
          bash build.sh
        shell: bash
      

