name: CI build

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container: moveit/moveit2:galactic-release
    steps:
      - uses: actions/checkout@v2
      - run: |
          ls
          export COLCON_WS=${GITHUB_WORKPACE}/ROS
      - run: |
          bash prepare_build.sh
          bash build.sh
        name: configure ws and build ros packages
