
name: CI build

on:
  pull_request:
  push:
    branches:
      - main
      - ci

jobs:
  build:
    runs-on: ubuntu-latest
    container: moveit/moveit2:galactic-source
    steps:
      - uses: actions/checkout@v2
      - name: prepare and build
        run: |
          export COLCON_WS=${GITHUB_WORKSPACE}/ROS
          bash build.sh
        shell: bash
      

